const ActionTypes = {
  UPDATE_A: "UPDATE_A",
  UPDATE_B: "UPDATE_B",
  UPDATE_C: "UPDATE_C",
  UPDATE_COLOR: "UPDATE_COLOR",
  ADD_FUNCTION: "ADD_FUNCTION",
  REMOVE_FUNCTION: "REMOVE_FUNCTION",
};

export default ActionTypes;
