const ActionTypes = {
  UPDATE_A: "UPDATE_A",
  UPDATE_B: "UPDATE_B",
  UPDATE_C: "UPDATE_C",
  UPDATE_COLOR: "UPDATE_COLOR",
  ADD_FUNCTION: "ADD_FUNCTION",
  REMOVE_FUNCTION: "REMOVE_FUNCTION",
  UPDATE_SCALE_X: "UPDATE_SCALE_X",
  UPDATE_SCALE_Y: "UPDATE_SCALE_Y",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL_AND_CANCEL: "CLOSE_MODAL_AND_CANCEL",
  CLOSE_MODAL_AND_SAVE: "CLOSE_MODAL_AND_SAVE",
};

export default ActionTypes;
